import Image from "next/image";
import "./globals.css";

export const metadata = {
  title: "Portfolio - Rizky Setiawan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-black">
        {/* navbar */}
        <div className=" text-white container mx-auto sm:px-12 px-6 sm:pt-10 pt-4">
          <div className="flex items-center justify-between">
            <p className="roboto-serif font-bold text-2xl tracking-wide">
              <a href="/"> vincent.</a>
            </p>

            <div className="flex items-center">
              <div className="dropdown sm:hidden mx-2 dropdown-end">
                <label tabIndex={0} className="btn btn-ghost">
                  <Image src="/language.svg" alt="language" width={28} height={28} />
                </label>
                <ul tabIndex={0} className="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
                  <li>
                    <a>
                      {" "}
                      <Image src="/gb.svg" alt="gb" width={20} height={20} /> English
                    </a>
                  </li>
                  <li>
                    <a>
                      <Image src="/id.svg" alt="id" width={20} height={20} /> Indonesia
                    </a>
                  </li>
                </ul>
              </div>
              <div className="dropdown dropdown-end sm:hidden ">
                <label tabIndex={1} className="">
                  <Image src="burger.svg" alt="burger" width={23} height={23} />
                </label>
                <ul tabIndex={1} className="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
                  <li className="mx-8 roboto-serif text-xl hover:text-white/60">
                    <a href="#">Home</a>{" "}
                  </li>
                  <li className="mx-8 roboto-serif text-xl hover:text-white/60">
                    <a href="#">Projects</a>{" "}
                  </li>
                  <li className="mx-8 roboto-serif text-xl hover:text-white/60">
                    <a href="#">Tech</a>{" "}
                  </li>
                  <li className="mx-8 roboto-serif text-xl hover:text-white/60">
                    <a href="#">Contact</a>{" "}
                  </li>
                </ul>
              </div>
            </div>

            <ul className="sm:flex hidden  items-center">
              <li className="mx-8 roboto-serif text-xl hover:text-white/60">
                <a href="#">Home</a>{" "}
              </li>
              <li className="mx-8 roboto-serif text-xl hover:text-white/60">
                <a href="#">Projects</a>{" "}
              </li>
              <li className="mx-8 roboto-serif text-xl hover:text-white/60">
                <a href="#">Tech</a>{" "}
              </li>
              <li className="mx-8 roboto-serif text-xl hover:text-white/60">
                <a href="#">Contact</a>{" "}
              </li>
              <li>
                <div className="dropdown dropdown-end">
                  <label tabIndex={0} className="btn btn-ghost">
                    <Image src="/language.svg" alt="language" width={28} height={28} />
                  </label>
                  <ul tabIndex={0} className="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
                    <li>
                      <a>
                        {" "}
                        <Image src="/gb.svg" alt="gb" width={20} height={20} /> English
                      </a>
                    </li>
                    <li>
                      <a>
                        <Image src="/id.svg" alt="id" width={20} height={20} /> Indonesia
                      </a>
                    </li>
                  </ul>
                </div>
              </li>
            </ul>
          </div>
        </div>
        {children}
        <footer className="footer px-10 py-4 border-t bg-transparent text-base-content border-base-300 roboto-serif">
          <div className="items-center grid-flow-col">
            <p>
              i’m currently listening to <br />
              <p className="flex py-1">
              <Image src="/spty.svg" alt="spty" width={24} height={24} className="pr-1" /> <p className="font-bold"> Not Playing </p> - Spotify
              </p>
            </p>
          </div>
          <div className="md:place-self-center md:justify-self-end">
            <div className="grid grid-flow-col gap-4 items-center">
              <a>
                <Image src="/instagram.svg" alt="instagram" width={36} height={36} />
              </a>
              <a>
                <Image src="/mail.svg" alt="mail" width={36} height={36} />
              </a>
              <a>
                <a className="btn bg-white text-black hover:text-white">Contact</a>
              </a>
            </div>
          </div>
        </footer>
        <footer className="footer footer-center p-4 bg-transparent text-base-content roboto-serif">
          <div>
            <p>Portfolio | Rizky Setiawan</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
